---

- name: Transfer puppet.modules.sh
  become: yes
  ansible.builtin.copy:
    src: puppet.modules.sh
    dest: /tmp
    mode: 0777

- name: Transfer setup.pp
  ansible.builtin.copy:
    src: setup.pp
    dest: /tmp
    mode: 0777

- name: Transfer manifest.pp
  ansible.builtin.copy:
    src: manifest.pp
    dest: /tmp
    mode: 0777

    #- name: Script modules
    #  command: sh /tmp/puppet.modules.sh
    #  ignore_errors: yes

- name: Create a folder on remote /storage/dteam/
  ansible.builtin.file:
    path: /storage/dteam
    state: directory
    owner: root
    group: root
    mode: '0700'

    #- name: Export path
    #  become: yes
    #  command: export PATH=${PATH}:/opt/puppet/bin

- name: Execute the 1/8 puppet modules
  #become: yes
  #ansible.builtin.command: puppet module install puppet-epel
  community.general.puppet:
    tags:
    - puppet-epel 
  ignore_errors: yes

- name: test installation
  command: puppet module install cnafsd-umd4
  ignore_errors: yes

- name: Execute the 2/8 puppet module
  #become: yes
  community.general.puppet:
    tags:
    - cnafsd-umd4
  ignore_errors: yes
  
- name: Execute the 3/8 puppet module
  #become: yes
  community.general.puppet:
    tags:
    - puppetlabs-ntp
  ignore_errors: yes
  
- name: Execute the 4/8 puppet module
  #become: yes
  community.general.puppet:
    tags:
    - puppet-fetchcrl 
  ignore_errors: yes
  
- name: Execute the 5/8 puppet module
  #become: yes
  community.general.puppet:
    tags:
    - lcgdm-voms
  ignore_errors: yes

- name: Execute the 6/8 puppet module
  #become: yes
  community.general.puppet:
    tags:
    - cnafsd-bdii
  ignore_errors: yes

- name: Execute the 7/8 puppet module
  #become: yes
  community.general.puppet:
    tags:
    - cnafsd-storm
  ignore_errors: yes

- name: Execute the 8/8 puppet module
  #become: yes
  community.general.puppet:
    tags:
    - cnafsd-lcmaps
  ignore_errors: yes
 
- name: Install redis
  ansible.builtin.yum:
    name:
      - redis
    state: present

- name: Enable redis
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes

- name: Execute the script setup.pp
  #become: yes
  command: puppet apply /tmp/setup.pp

- name: Execute the script manifest. Need configuration in the file
  #become: yes
  command: puppet apply /tmp/manifest.pp

- name: Create a folder on remote /storm/webdav
  ansible.builtin.file:
    path: /etc/storm/webdav
    state: directory
    owner: root
    group: storm
    mode: '0700'

- name: Transfer storm-webdav-test-sa.properties
  ansible.builtin.copy:
    src: storm-webdav-test-sa.properties
    dest: /etc/storm/webdav/sa.d/
    mode: 0644
    
- name: Transfer application.yml 
  ansible.builtin.copy:
    src: application.yml 
    dest: /etc/storm/webdav/config/
    mode: 0640

- name: Copy certificates to storm folder.
  copy:
    src: /etc/grid-security/
    dest: /etc/grid-security/storm-webdav/
    delegate_to: localhost
