---

- name: Create group "storm"
  ansible.builtin.group:
    name: storm
    state: present

- name: Add the user 'storm'
  ansible.builtin.user:
    name: storm
    comment: Storm User
    group: storm

- name: Set a hostname
  ansible.builtin.hostname:
    name: spsrc_1.local

- name: Install Common Packages
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - acl
    - attr
    - openssl
    - wget
    - gcc
    - libffi-devel
    - python-devel
    - dnf
    - python2-cryptography.x86_64
    - yum-utils
    state: present

- name: Install NTP
  ansible.builtin.package:
    name: ntp
    state: present

- name: Enable ntpd
  ansible.builtin.systemd:
    name: ntpd
    state: started
    enabled: yes

- name: Install python-crypto with dnf
  ansible.builtin.dnf:
    name:
      - python-crypto
    state: latest

- name: Create a folder for certificates
  ansible.builtin.file:
    path: /etc/grid-security/
    state: directory
    owner: root
    group: root
    mode: '0754'
   
    #Certificados x509

- name: Create private key
  community.crypto.openssl_privatekey:
    path: /etc/grid-security/hostkey.pem
    size: 2048
    mode: 0400
    type: RSA

- name: Create public key
  community.crypto.x509_certificate:
    path: /etc/grid-security/hostcert.crt
    privatekey_path: /etc/grid-security/hostkey.pem
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    #mode: 0600

- name: Create self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/grid-security/hostcert.pem
    privatekey_path: /etc/grid-security/hostkey.pem
    provider: selfsigned
    mode: 0644

- name: Create a folder on remote host for temporal files
  ansible.builtin.file:
    path: /tmp
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Import key from UMG
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY

- name: Install epel-release-7-12
  become: yes
  ansible.builtin.yum:
    name: https://download-ib01.fedoraproject.org/pub/epel/7/aarch64/Packages/e/epel-release-7-12.noarch.rpm
    state: present

- name: Install umd-release
  become: yes
  ansible.builtin.yum:
    name: http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
    state: present

- name: Add repository EGI (new url)
  become: yes
  ansible.builtin.yum_repository:
    name: EGI-trustanchors
    description: EGI-trustanchors repo
    baseurl: http://repository.egi.eu/sw/production/cas/1/current/
    state: present

- name: Import key from EGI repository
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: http://repository.egi.eu/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3

- name: yum-clean-metadata
  ansible.builtin.command: yum clean metadata
  args:
    warn: no
  
- name: Update lcg-CA
  become: yes
  command: yum update lcg-CA

- name: Install ca-policy-egi-core
  become: yes
  ansible.builtin.yum:
    name: ca-policy-egi-core
    state: present

- name: Install yum-utils
  become: yes
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Install epel-release
  ansible.builtin.package:
    name: epel-release
    state: latest

- name: Install storm-webdav
  ansible.builtin.package:
    name: storm-webdav
    state: present

- name: Remove previous version Puppet5
  ansible.builtin.package:
    name: puppet5-release
    state: absent

- name: Install Puppet 5 
  become: yes
  command: rpm -Uvh https://yum.puppetlabs.com/puppet5/el/7/x86_64/puppet5-release-5.0.0-6.el7.noarch.rpm

- name: Check repo puppet
  become: yes
  ansible.builtin.copy:
    src: puppet5.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Copy Storm stable repo
  become: yes
  ansible.builtin.copy:
    src: storm-stable-centos7.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Copy Storm beta repo
  become: yes
  ansible.builtin.copy:
    src: storm-beta-centos7.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Copy Storm nightly repo
  become: yes
  ansible.builtin.copy:
    src: storm-nightly-centos7.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Install Puppet 
  #become: yes
  ansible.builtin.package:
    name: puppet
    state: present

- name: reset ssh connection
  meta: reset_connection

- name: Export Path
  command: export PATH=${PATH}:/opt/puppet/bin
  ignore_errors: yes

- name: Reboot the machine (Wait for 1 min)
  reboot:
    reboot_timeout: 60

