---
- name: Install Packages
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - acl
    - attr
    - openssl
    - epel-release
    - python-pip
    state: present

- name: Install NTP
  ansible.builtin.package:
    name: ntp
    state: present

- name: Enable ntpd
  ansible.builtin.systemd:
    name: ntpd
    state: started
    enabled: yes
    #when: ansible_os_family == 'RedHat'
    #ignore_errors: True

- name: Upgrade RHEL Family OS packages
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Create a folder on remote host
  ansible.builtin.file:
    path: /etc/grid-security/
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Install Python libraries cryptography
  ansible.builtin.package:
    name: "{{ packages1 }}"
  vars:
    packages1:
    - gcc
    - libffi-devel
    - python-devel
    - pyOpenSSL
    state: present

- name: Upgrade pip
  yum:
    name: 'python-pip'
    state: latest
  when: ansible_os_family == "RedHat"


  #- name: Install python package
  #  ansible.builtin.pip:
  #    name: cryptography
  #    executable: pip 

    #- name: Create simple self-signed certificate
    #  community.crypto.x509_certificate:
    #    path: /etc/grid-security/certificate.pem
    #    privatekey_path: /etc/grid-security/certificate.key
    #    provider: selfsigned

    #- name: Change permissions
    #  ansible.builtin.file:
    #    path: /etc/grid-security/certificate.pem
    #    owner: root
    #    group: root
    #    mode: '0644'

    #- name: Change permissions
    #  ansible.builtin.file:
    #    path: /etc/grid-security/certificate.key
    #    owner: root
    #    group: root
    #    mode: '0400'

- name: Create a folder on remote host for temporal files
  ansible.builtin.file:
    path: /tmp
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY

- name: Install remote rpm files on server
  ansible.builtin.yum:
    name: https://download-ib01.fedoraproject.org/pub/epel/7/aarch64/Packages/e/epel-release-7-12.noarch.rpm
    state: present
    
    #- name: Copy rpm files to server
    #  ansible.builtin.copy:
    #    src: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-12.noarch.rpm
    #    dest: /tmp/epel-release-7-12.noarch.rpm

- name: Copy rpm files to server
  ansible.builtin.copy:
    src: http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
    dest: /tmp/umd-release-4.1.3-1.el7.centos.noarch.rpm

- name: Install packages.
  yum:
     name: /tmp/epel-release-7-12.noarch.rpm
     state: present

- name: Install packages.
  yum:
     name: /tmp/umd-release-4.1.3-1.el7.centos.noarch.rpm
     state: present

- name: Download EGI-trustanchors
  ansible.builtin.get_url:
    url: http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo
    dest: /etc/yum.repos.d/EGI-trustanchors.repo
    mode: '0440'

- name: Install ca-policy-egi-core and yum utils
  ansible.builtin.yum:
    name:
      - ca-policy-egi-core
      - yum-utils
    state: present

- name: Add repository
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo

- name: Install epel-release
  ansible.builtin.yum:
    name:
      - epel-release
    state: present

- name: Install package puppet
  community.general.apt_rpm:
    pkg: https://yum.puppetlabs.com/puppet5/el/7/x86_64/puppet5-release-5.0.0-6.el7.noarch.rpm
    state: present

- name: Install puppet
  ansible.builtin.yum:
    name:
      - puppet
    state: present

- name: Transfer puppet.modules.sh
  ansible.builtin.copy:
    src: puppet.modules.sh
    dest: /tmp 
    mode: 0777

- name: Execute the script
  ansible.builtin.shell: puppet.modules.sh >> puppet.modules.txt
  args:
    chdir: tmp/
    #creates: puppet.modules.txt


- name: Transfer setup.pp
  ansible.builtin.copy:
    src: setup.pp
    dest: /tmp
    mode: 0777

- name: Execute the script
  command: puppet apply /tmp/setup.pp
