---


- name: Install Common Packages
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - acl
    - attr
    - openssl
    - wget  
    - gcc
    - libffi-devel
    - python-devel
    - dnf
    - python2-cryptography.x86_64
    - yum-utils
    state: present

- name: Install NTP
  ansible.builtin.package:
    name: ntp
    state: present

- name: Enable ntpd
  ansible.builtin.systemd:
    name: ntpd
    state: started
    enabled: yes

    #Funciona, comentado para segur
    #- name: Install openssl and python-pip
    #  ansible.builtin.package:
    #    name: 
    #     - openssl
    #     - python-pip
    #    state: present

- name: Install python-crypto with dnf
  ansible.builtin.dnf:
    name: 
      - python-crypto  
    state: latest

- name: Create a folder on remote host
  ansible.builtin.file:
    path: /etc/grid-security/
    state: directory
    owner: root
    group: root
    mode: '0700'

    #- name: Upgrade RHEL Family OS packages
    #  yum:
    #    name: '*'
    #    state: latest
    #  when: ansible_os_family == "RedHat"

  # Certificados x509

- name: Ensure private key is present
  community.crypto.openssl_privatekey:
    path: /etc/grid-security/hostkey.pem
    size: 2048
    mode: 0400
    type: RSA

- name: Ensure self-signed cert is present
  community.crypto.x509_certificate:
    path: /etc/grid-security/hostcert.crt
    privatekey_path: /etc/grid-security/hostkey.pem
    provider: selfsigned
    selfsigned_not_after: "+3650d" 
    #mode: 0600

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/grid-security/hostcert.pem
    privatekey_path: /etc/grid-security/hostkey.pem
    provider: selfsigned
    mode: 0644

- name: Create a folder on remote host for temporal files
  ansible.builtin.file:
    path: /tmp
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Import key from UMG
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY

- name: Install epel-release-7-12
  become: yes
  ansible.builtin.yum:   
          #name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-14.noarch.rpm
    name: https://download-ib01.fedoraproject.org/pub/epel/7/aarch64/Packages/e/epel-release-7-12.noarch.rpm
    state: present
    
- name: Install umd-release
  become: yes
  ansible.builtin.yum:
    name: http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
    state: present

- name: Add repository EGI (Before Sep/2022)
  become: yes
  ansible.builtin.yum_repository:
    name: EGI-trustanchors
    description: EGI-trustanchors repo
    baseurl: http://repository.egi.eu/sw/production/cas/1/current/
    state: present

- name: Import key from EGI
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: http://repository.egi.eu/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3
    
- name: yum-clean-metadata
  ansible.builtin.command: yum clean metadata
  args:
    warn: no

- name: Update lcg-CA
  become: yes
  command: yum update lcg-CA

- name: Install ca-policy-egi-core
  become: yes
  ansible.builtin.yum:
    name: ca-policy-egi-core
    state: present

- name: Install yum-utils
  become: yes
  ansible.builtin.yum:
    name: yum-utils
    state: present

  # Error en el repo, no puede traerlo, se copia fichero
  #- name: config-manager
  #  become: yes
  #command: wget https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo -O /etc/yum.repos.d/storm-stable-centos7.repo
  #command: yum-config-manager --add-repo https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo

- name: Install epel-release
  ansible.builtin.package:
    name: epel-release
    state: present

    #- name: Test install latest version puppet from rpm
    #  become: yes
    #  command: rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm

- name: Install puppet
  become: yes
  ansible.builtin.yum:
    name: https://yum.puppetlabs.com/puppet5/el/7/x86_64/puppet5-release-5.0.0-6.el7.noarch.rpm
    state: present

- name: Install Puppet
  become: yes
  ansible.builtin.package:
    name: puppet
    state: present


  #- name: Add repo Cloud Cnaf
  #  become: yes
  #  ansible.builtin.yum_repository:
  #    name: storm
  #    description: Cloud Cnaf
  #    baseurl: https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo

    #- name: Get Cloud Cnaf Repo File
    #  become: yes
    #  ansible.builtin.copy:
    #    src: storm-stable-centos7.repo
    #    dest: /etc/yum.repos.d/
    #    mode: 0644

    #
    #- name: wget Cloud Cnaf Repo
    #  become: yes
    #  command: wget https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo -O /etc/yum.repos.d/storm-stable-centos7.repo

    # Check if it is needed
    #- name: Install puppet-agent
    #  ansible.builtin.yum:
    #    name:
    #      - puppet-agent
    #    state: present

- name: reset ssh connection 
  meta: reset_connection    

- name: Transfer puppet.modules.sh
  become: yes
  ansible.builtin.copy:
    src: puppet.modules.sh
    dest: /tmp 
    mode: 0777

- name: Transfer setup.pp
  ansible.builtin.copy:
    src: setup.pp
    dest: /tmp
    mode: 0777

- name: Transfer manifest.pp
  ansible.builtin.copy:
    src: manifest.pp
    dest: /tmp
    mode: 0777

- name: Reboot the machine (Wait for 2 min)
  reboot:
    reboot_timeout: 120

- name: Execute the script puppet.modules
  become: yes
  command: sh /tmp/puppet.modules.sh  

- name: Execute the script setup.pp
  become: yes
  command: puppet apply /tmp/setup.pp

- name: Execute the scritp manifest
  become: yes
  command: puppet apply /tmp/manifest.pp

- name: Install redis
  ansible.builtin.yum:
    name:
      - redis
    state: present

- name: Enable redis
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes
