---
- name: Install Packages
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
    - acl
    - attr
    - openssl
<<<<<<< Updated upstream
=======
    - wget  
    - gcc
    - libffi-devel
    - python-devel
    - dnf
    - python2-cryptography.x86_64
    - yum-utils
>>>>>>> Stashed changes
    state: present

- name: Install NTP
  ansible.builtin.package:
    name: ntp
    state: present

- name: Enable ntpd
  ansible.builtin.systemd:
    name: ntpd
    state: start
    enabled: yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: True

- name: Create a folder on remote host
  ansible.builtin.file:
    path: /etc/grid-security/
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/grid-security/certificate.pem
    privatekey_path: /etc/grid-security/certificate.key
    provider: selfsigned

- name: Change permissions
    file:
       path: /etc/grid-security/certificate.pem
       owner: root
       group: root
       mode: '0644'
    file:
       path: /etc/grid-security/certificate.key
       owner: root
       group: root
       mode: '0400'

- name: Create a folder on remote host for temporal files
  ansible.builtin.file:
    path: /tmp
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY

<<<<<<< Updated upstream
- name: Copy rpm files to server
  copy:
     src: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-12.noarch.rpm
     dest: /tmp/epel-release-7-12.noarch.rpm
     src: http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
     dest: /tmp/umd-release-4.1.3-1.el7.centos.noarch.rpm
=======
- name: Install remote rpm files on server (EPEL)
  become: yes
  ansible.builtin.yum:   
          #name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-14.noarch.rpm
    name: https://download-ib01.fedoraproject.org/pub/epel/7/aarch64/Packages/e/epel-release-7-12.noarch.rpm
    state: present
    
- name: Install umd-release
  become: yes
  ansible.builtin.yum:
    name: http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
    state: present

    #- name: Wget EGI Repo
    #  become: yes
    #  command: wget http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo -O /etc/yum.repos.d/EGI-trustanchors.repo

- name: Add repository EGI (Before Sep/2022)
  become: yes
  ansible.builtin.yum_repository:
    name: EGI-trustanchors
    description: EGI-trustanchors repo
    baseurl: http://repository.egi.eu/sw/production/cas/1/current/
    state: present

- name: Import a key from EGI
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: http://repository.egi.eu/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3
    
- name: Clean cache metadata
  become: yes
  command: yum clean cache metadata

- name: Update lcg-CA
  become: yes
  command: yum update lcg-CA


- name: Install ca-policy-egi-core
  become: yes
  ansible.builtin.yum:
    name: ca-policy-egi-core
    state: present

- name: install yum-utils
  command: yum install yum-utils -y

  # Error en el repo, no puede traerlo, se copia fichero
  #- name: config-manager
  #  become: yes
  #command: wget https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo -O /etc/yum.repos.d/storm-stable-centos7.repo
  #command: yum-config-manager --add-repo https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo

- name: Install epel-release
  ansible.builtin.package:
    name: epel-release
    state: present

- name: install rpm puppets
  command: rpm -Uvh https://yum.puppetlabs.com/puppet5/el/7/x86_64/puppet5-release-5.0.0-6.el7.noarch.rpm


  #- name: Add repo Cloud Cnaf
  #  become: yes
  #  ansible.builtin.yum_repository:
  #    name: storm
  #    description: Cloud Cnaf
  #    baseurl: https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo

    #- name: Get Cloud Cnaf Repo File
    #  become: yes
    #  ansible.builtin.copy:
    #    src: storm-stable-centos7.repo
    #    dest: /etc/yum.repos.d/
    #    mode: 0644

    #
    #- name: wget Cloud Cnaf Repo
    #  become: yes
    #  command: wget https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo -O /etc/yum.repos.d/storm-stable-centos7.repo

    #- name: Wget EGI Repo
    #  become: yes
    #  command: wget http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo -O /etc/yum.repos.d/EGI-trustanchors.repo
  #register: out
  #- debug: var=out.stdout_lines
>>>>>>> Stashed changes

- name: Install packages.
  yum:
     name: /tmp/epel-release-7-12.noarch.rpm
     name: /tmp/umd-release-4.1.3-1.el7.centos.noarch.rpm
     state: present

- name: Download EGI-trustanchors
  ansible.builtin.get_url:
    url: http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo
    dest: /etc/yum.repos.d/EGI-trustanchors.repo
    mode: '0440'

<<<<<<< Updated upstream
- name: Install ca-policy-egi-core and yum utils
  ansible.builtin.yum:
    name:
      - ca-policy-egi-core
      - yum-utils
    state: present
=======
>>>>>>> Stashed changes

- name: Add repository
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://repo.cloud.cnaf.infn.it/repository/storm/storm-stable-centos7.repo

- name: Install epel-release
  ansible.builtin.yum:
    name:
      - epel-release
    state: present

- name: Install package puppet
  community.general.apt_rpm:
    pkg: https://yum.puppetlabs.com/puppet5/el/7/x86_64/puppet5-release-5.0.0-6.el7.noarch.rpm
    state: present

- name: Install puppet
  ansible.builtin.yum:
    name:
      - puppet
    state: present


- name: Transfer and execute puppet.modules.sh
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=puppet.modules.sh dest=/tmp mode=0777

     - name: Execute the script
       command: sh /tmp/puppet.modules.sh

- name: Transfer setup.pp
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=setup.pp dest=/tmp mode=0777

<<<<<<< Updated upstream
     - name: Execute the script
       command: puppet apply /tmp/setup.pp
=======
- name: Execute the script puppet.modules
  become: yes
  command: sh /tmp/puppet.modules.sh  

- name: Execute the script setup.pp
  become: yes
  command: puppet apply /tmp/setup.pp

- name: Execute the scritp manifest
  become: yes
  command: puppet apply /tmp/manifest.pp

- name: Install redis
  ansible.builtin.yum:
    name:
      - redis
    state: present

- name: Enable redis
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes
>>>>>>> Stashed changes
